# Generated by Django 4.1.2 on 2022-10-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHIP_to', models.CharField(max_length=100, null=True, unique=True)),
                ('BILL_to', models.CharField(max_length=100, null=True)),
                ('Customer_code', models.CharField(max_length=100, null=True)),
                ('Deliver_Term', models.CharField(max_length=100, null=True)),
                ('Contact_info', models.CharField(max_length=100, null=True)),
                ('Payment_Term', models.CharField(max_length=100, null=True)),
                ('IPU_fty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='mill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MILL', models.CharField(max_length=20, null=True, unique=True)),
                ('Mill_Code', models.CharField(max_length=20, null=True)),
                ('Payment_Term', models.CharField(max_length=20, null=True)),
                ('IPU_mill', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='zoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZOH', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='fabPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_No', models.CharField(max_length=100)),
                ('PO_Recieved_Date', models.DateField(blank=True, null=True)),
                ('BC_PO_Date', models.DateField(blank=True, null=True)),
                ('BC_PO_No', models.CharField(blank=True, max_length=200, null=True)),
                ('Discription', models.CharField(max_length=1000, null=True)),
                ('Content', models.CharField(max_length=1000, null=True)),
                ('Order_Qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('Coo', models.CharField(choices=[('CHINA', 'CHINA'), ('INDIA', 'INDIA'), ('TURKEY', 'TURKEY'), ('VIETNAM', 'VIETNAM'), ('OTHERS', 'OTHERS')], max_length=200, null=True)),
                ('Full_width_cm', models.IntegerField(null=True)),
                ('Cuttable_Width_cm', models.IntegerField(null=True)),
                ('Weight_GSM', models.IntegerField(null=True)),
                ('Yarn_Size', models.CharField(max_length=200, null=True)),
                ('Season', models.CharField(max_length=200, null=True)),
                ('PIC', models.CharField(blank=True, max_length=200, null=True)),
                ('Fabric_source', models.CharField(blank=True, max_length=200, null=True)),
                ('Comment', models.CharField(max_length=2000, null=True)),
                ('Peerless_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('Cost_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('Mill_Orig_Ex_Mill', models.DateField(blank=True, null=True)),
                ('Mill_Current_Ex_mill', models.DateField(blank=True, null=True)),
                ('Peerless_Orig_Ex_Mill', models.DateField(blank=True, null=True)),
                ('Peerless_Current_Ex_mill', models.DateField(blank=True, null=True)),
                ('SO_No', models.CharField(blank=True, max_length=200, null=True)),
                ('Shipped_Qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('SS_Approval', models.CharField(blank=True, max_length=1000, null=True)),
                ('RC_CL_Approval', models.CharField(blank=True, max_length=1000, null=True)),
                ('PI_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('ETD', models.CharField(blank=True, max_length=1000, null=True)),
                ('ETA', models.DateField(blank=True, null=True)),
                ('Inv_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Payment_sts', models.BooleanField(default=False)),
                ('Order_status', models.CharField(choices=[('SHIP', 'SHIP'), ('OPEN', 'OPEN')], max_length=200, null=True)),
                ('Mill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FAB_SALE.mill')),
                ('Ship_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FAB_SALE.factory')),
                ('Zoh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FAB_SALE.zoh')),
            ],
        ),
    ]
