# Generated by Django 4.1.2 on 2022-10-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAB_SALE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabpo',
            name='Freight_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
