# Generated by Django 4.1.2 on 2022-10-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAB_SALE', '0002_fabpo_freight_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='Destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
