# Generated by Django 4.1.2 on 2022-12-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAB_SALE', '0003_factory_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoh',
            name='Type',
            field=models.CharField(choices=[('CK Lauren Zhen Xiang', 'CK Lauren Zhen Xiang'), ('GAB open order', 'GAB open order'), ('Open Orders', 'Open Orders'), ('Wool 52 Poly Spandex', 'Wool 52 Poly Spandex'), ('Wool Material Open Orders', 'Wool Material Open Orders'), ('Wool rich 70 blend polyester', 'Wool rich 70 blend polyester')], max_length=200, null=True),
        ),
    ]
